# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.7.2
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-11-29T10:37:17Z"
  labels:
    app: pw
  name: pw
spec:
  containers:
  - command:
    - google-chrome
    env:
    - name: DISPLAY
      value: :0
    image: localhost/playwright:v1
    name: playwright
    securityContext:
      runAsGroup: 1000
      runAsUser: 1000
    stdin: true
    tty: true
    volumeMounts:
    - mountPath: /tmp/.X11-unix
      name: tmp-.X11-unix-host-0
  volumes:
  - hostPath:
      path: /tmp/.X11-unix
      type: Directory
    name: tmp-.X11-unix-host-0
